# SELECT A.AUTHOR_ID, A.AUTHOR_NAME, B.CATEGORY, (B.PRICE * TEMP.SALES) AS TOTAL_SALES
# FROM BOOK B
# JOIN (
#     SELECT BOOK_ID, SUM(SALES) AS SALES
#     FROM BOOK_SALES
#     WHERE SALES_DATE LIKE '2022-01-%'
#     GROUP BY BOOK_ID    
# ) AS TEMP ON B.BOOK_ID = TEMP.BOOK_ID
# JOIN AUTHOR A
# ON B.AUTHOR_ID = A.AUTHOR_ID
# GROUP BY     A.AUTHOR_ID, A.AUTHOR_NAME, B.CATEGORY
# ORDER BY A.AUTHOR_ID ASC, B.CATEGORY DESC;

SELECT 
    A.AUTHOR_ID, 
    A.AUTHOR_NAME, 
    B.CATEGORY, 
    SUM(B.PRICE * S.SALES) AS TOTAL_SALES
FROM BOOK B
JOIN BOOK_SALES S 
    ON B.BOOK_ID = S.BOOK_ID
JOIN AUTHOR A 
    ON B.AUTHOR_ID = A.AUTHOR_ID
WHERE S.SALES_DATE BETWEEN '2022-01-01' AND '2022-01-31'
GROUP BY 
    A.AUTHOR_ID, 
    A.AUTHOR_NAME, 
    B.CATEGORY
ORDER BY 
    A.AUTHOR_ID ASC, 
    B.CATEGORY DESC;
