SELECT A.ID
FROM ECOLI_DATA A
LEFT JOIN ECOLI_DATA B ON A.PARENT_ID = B.ID
LEFT JOIN ECOLI_DATA C ON B.PARENT_ID = C.ID
LEFT JOIN ECOLI_DATA D ON C.PARENT_ID = D.ID
WHERE C.ID IS NOT NULL AND D.ID IS NULL
ORDER BY A.ID ASC;