SELECT P.PRODUCT_CODE, SUM(S.SALES_AMOUNT * P.PRICE) AS SALES
FROM OFFLINE_SALE S
JOIN PRODUCT P ON S.PRODUCT_ID = P.PRODUCT_ID
GROUP BY S.PRODUCT_ID, P.PRODUCT_CODE
ORDER BY SALES DESC, P.PRODUCT_CODE ASC;
#SUM(amount * price) -> 각 행마다 계산 후 더함