SELECT 
    DATE_FORMAT(T.SALES_DATE, '%Y-%m-%d') AS SALES_DATE,
    T.PRODUCT_ID,
    T.USER_ID,
    T.SALES_AMOUNT
FROM (
    SELECT 
        SALES_DATE,
        PRODUCT_ID,
        USER_ID,
        SALES_AMOUNT
    FROM ONLINE_SALE
    WHERE SALES_DATE >= '2022-03-01'
      AND SALES_DATE < '2022-04-01'

    UNION ALL

    SELECT 
        SALES_DATE,
        PRODUCT_ID,
        NULL AS USER_ID,
        SALES_AMOUNT
    FROM OFFLINE_SALE
    WHERE SALES_DATE >= '2022-03-01'
      AND SALES_DATE < '2022-04-01'
) T
ORDER BY T.SALES_DATE ASC, T.PRODUCT_ID ASC, T.USER_ID ASC;