SELECT  C.CAR_ID, C.CAR_TYPE, ROUND(C.DAILY_FEE * 30 * (100 - P.DISCOUNT_RATE) / 100) AS FEE
FROM CAR_RENTAL_COMPANY_CAR C
JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN P ON C.CAR_TYPE = P.CAR_TYPE
WHERE C.CAR_TYPE IN ('세단', 'SUV') 
AND C.CAR_ID NOT IN(
    SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE START_DATE < '2022-12-01' AND '2022-11-01' <= END_DATE 
)
AND P.DURATION_TYPE = '30일 이상'
HAVING FEE >= 500000 AND FEE < 2000000
ORDER BY FEE DESC, C.CAR_TYPE ASC, C.CAR_ID DESC;

# SELECT * 
# FROM CAR_RENTAL_COMPANY_CAR C
# LEFT JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY H ON C.CAR_ID = H.CAR_ID
# WHERE C.CAR_TYPE IN ('세단', 'SUV') AND C.CAR_ID NOT IN (
#     SELECT CAR_ID
#     FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
#     WHERE START_DATE <= '2022-11-30' AND '2022-11-01' <= END_DATE
# )
# 2022년 11월 1일부터 2022년 11월 30일 ->
# 대여 시작일이 11월 30일 이하이고
# 대여 종료일이 11월 1일 이상이면
# 11월 기간과 하루라도 겹침