#18
WITH RANKED AS(
    SELECT ID, 
        NTILE(4) OVER (ORDER BY SIZE_OF_COLONY DESC) AS BUCKET
    FROM ECOLI_DATA
)
SELECT R.ID, 
    CASE R.BUCKET
        WHEN 1 THEN 'CRITICAL'
        WHEN 2 THEN 'HIGH'
        WHEN 3 THEN 'MEDIUM'
        ELSE 'LOW'
    END AS COLONY_NAME
FROM RANKED R
JOIN ECOLI_DATA D ON R.ID = D.ID
ORDER BY R.ID ASC;