#49
SELECT YEAR(SALES_DATE), MONTH(SALES_DATE), I.GENDER, COUNT(DISTINCT S.USER_ID) AS USERS
FROM ONLINE_SALE S
JOIN USER_INFO I ON S.USER_ID = I.USER_ID
WHERE I.GENDER IS NOT NULL
GROUP BY YEAR(SALES_DATE), MONTH(SALES_DATE), I.GENDER
ORDER BY YEAR(SALES_DATE), MONTH(SALES_DATE), I.GENDER ASC;
