SELECT A.TEMP AS FISH_COUNT, FNI.FISH_NAME
FROM FISH_NAME_INFO FNI
LEFT JOIN (
    SELECT FISH_TYPE, COUNT(FISH_TYPE) AS TEMP
    FROM FISH_INFO 
    GROUP BY FISH_TYPE
) AS A
ON FNI.FISH_TYPE = A.FISH_TYPE
ORDER BY FISH_COUNT DESC;