#31
WITH RECURSIVE GENS AS (
    #START
    SELECT ID, 1 AS GEN
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL
    
    UNION ALL
    
    #RECURSIVE
    SELECT E.ID, G.GEN + 1
    FROM ECOLI_DATA E
    JOIN GENS G ON E.PARENT_ID = G.ID
),
CHILDREN AS (
    SELECT A.ID AS PARENT, B.ID AS CHILD
    FROM ECOLI_DATA A
    LEFT JOIN ECOLI_DATA B ON A.ID = B.PARENT_ID
)

# SELECT *
# FROM GENS

# SELECT *
# FROM CHILDREN

SELECT COUNT(*) AS COUNT, G.GEN AS GENERATION
FROM GENS G
LEFT JOIN CHILDREN C ON G.ID = C.PARENT
WHERE C.CHILD IS NULL
GROUP BY G.GEN