#31
SELECT O.PRODUCT_ID, P.PRODUCT_NAME, (SUM(O.AMOUNT) * P.PRICE)AS TOTAL_SALES
FROM FOOD_PRODUCT P
JOIN FOOD_ORDER O ON P.PRODUCT_ID = O.PRODUCT_ID
WHERE '2022-05-01' <= O.PRODUCE_DATE AND O.PRODUCE_DATE < '2022-06-01'
GROUP BY O.PRODUCT_ID, P.PRODUCT_NAME, P.PRICE
ORDER BY TOTAL_SALES DESC, O.PRODUCT_ID ASC;