SELECT ID, EMAIL, FIRST_NAME, LAST_NAME
FROM DEVELOPERS
WHERE (SKILL_CODE & (
    SELECT BIT_OR(CODE)
    FROM SKILLCODES
    WHERE CATEGORY = 'Front End'
)) > 0
ORDER BY ID ASC;

# SELECT BIT_OR(CODE) AS OR_RESULT
# FROM SKILLCODES
# WHERE CATEGORY = 'Front End';