#14
WITH BASE AS (
    SELECT E.EMP_NO, E.EMP_NAME, E.SAL,
        CASE
            WHEN AVG(G.SCORE) >= 96 THEN 'S'
            WHEN AVG(G.SCORE) >= 90 THEN 'A'
            WHEN AVG(G.SCORE) >= 80 THEN 'B'
            ELSE 'C'
        END AS GRADE
    FROM HR_GRADE G
    JOIN HR_EMPLOYEES E ON G.EMP_NO = E.EMP_NO
    GROUP BY E.EMP_NO, E.EMP_NAME, E.SAL
)
SELECT B.EMP_NO, B.EMP_NAME, B.GRADE, 
    CASE B.GRADE
        WHEN 'S' THEN B.SAL * 0.2
        WHEN 'A' THEN B.SAL * 0.15
        WHEN 'B' THEN B.SAL * 0.1
        ELSE 0
    END AS BONUS
FROM BASE B
JOIN HR_EMPLOYEES E ON B.EMP_NO = E.EMP_NO
ORDER BY B.EMP_NO ASC;
