SELECT I.ITEM_ID, I.ITEM_NAME, I.RARITY
# SELECT * 
FROM ITEM_INFO P
JOIN ITEM_TREE T ON P.ITEM_ID = T.PARENT_ITEM_ID
JOIN ITEM_INFO I ON T.ITEM_ID = I.ITEM_ID
WHERE P.RARITY = 'RARE'
ORDER BY I.ITEM_ID DESC;
