# select month(START_DATE) as MONTH, CAR_ID, count(CAR_ID) as RECORDS
# from CAR_RENTAL_COMPANY_RENTAL_HISTORY
# where 8 <= month(START_DATE) and month(START_DATE) <= 10
# group by month(START_DATE), CAR_ID
# having 5 <= count(CAR_ID)
# order by MONTH asc, CAR_ID desc;

SELECT 
    MONTH(START_DATE) AS MONTH,
    CAR_ID,
    COUNT(*) AS RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE START_DATE BETWEEN '2022-08-01' AND '2022-10-31'
  AND CAR_ID IN (
      SELECT CAR_ID
      FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
      WHERE START_DATE BETWEEN '2022-08-01' AND '2022-10-31'
      GROUP BY CAR_ID
      HAVING COUNT(*) >= 5
  )
GROUP BY MONTH(START_DATE), CAR_ID
ORDER BY MONTH ASC, CAR_ID DESC;