SELECT YEAR(D.DIFFERENTIATION_DATE) AS YEAR, T.MAX_SIZE - D.SIZE_OF_COLONY AS YEAR_DEV, D.ID
FROM ECOLI_DATA D
JOIN (
    SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR, MAX(SIZE_OF_COLONY) AS MAX_SIZE
    FROM ECOLI_DATA
    GROUP BY YEAR(DIFFERENTIATION_DATE)    
) AS T
ON YEAR(D.DIFFERENTIATION_DATE) = T.YEAR
ORDER BY YEAR ASC, YEAR_DEV ASC;