#42
# SELECT EMP_NO
# FROM HR_GRADE
# WHERE YEAR = '2022'
# GROUP BY EMP_NO
# ORDER BY SUM(SCORE) DESC
# LIMIT 1;
SELECT SUM(G.SCORE) AS SCORE, G.EMP_NO, E.EMP_NAME, E.POSITION, E.EMAIL
FROM HR_GRADE G
JOIN HR_EMPLOYEES E ON G.EMP_NO = E.EMP_NO
WHERE G.YEAR = '2022'
GROUP BY G.EMP_NO
ORDER BY SUM(G.SCORE) DESC
LIMIT 1;