SELECT HD.DEPT_ID, HD.DEPT_NAME_EN, A.AVG_SAL
FROM HR_DEPARTMENT HD
JOIN (
    SELECT DEPT_ID, ROUND(AVG(SAL), 0) AS AVG_SAL
    FROM HR_EMPLOYEES
    GROUP BY DEPT_ID
) AS A ON HD.DEPT_ID = A.DEPT_ID
ORDER BY A.AVG_SAL DESC;



# SELECT DEPT_ID, ROUND(AVG(SAL), 0)
# FROM HR_EMPLOYEES
# GROUP BY DEPT_ID;