# SELECT B.CATEGORY, SUM(B.BOOK_ID) AS TOTAL_SALES
SELECT B.CATEGORY, SUM(BS.SALES) AS TOTAL_SALES
FROM BOOK_SALES BS
LEFT JOIN BOOK B ON BS.BOOK_ID = B.BOOK_ID
WHERE BS.SALES_DATE BETWEEN '2022-01-01' AND '2022-01-31'
GROUP BY B.CATEGORY
ORDER BY B.CATEGORY ASC;