SELECT COUNT(FI.ID) AS FISH_COUNT, MAX(FI.LENGTH) AS MAX_LENGTH, FI.FISH_TYPE
FROM FISH_INFO FI
WHERE FI.FISH_TYPE IN (
    SELECT FISH_TYPE
    FROM FISH_INFO
    GROUP BY FISH_TYPE
    HAVING AVG(LENGTH) >= 33   
)
GROUP BY FI.FISH_TYPE
ORDER BY FI.FISH_TYPE ASC;