select a.BOOK_ID, b.AUTHOR_NAME, date_format(PUBLISHED_DATE, '%Y-%m-%d') as PUBLISHED_DATE
from BOOK a
inner join AUTHOR b on a.AUTHOR_ID = b.AUTHOR_ID
where a.CATEGORY = '경제'
order by PUBLISHED_DATE;

# SELECT B.BOOK_ID, A.AUTHOR_NAME, DATE_FORMAT(PUBLISHED_DATE, '%Y-%m-%d') as PUBLISHED_DATE
# FROM BOOK B JOIN AUTHOR A
# ON B.AUTHOR_ID = A.AUTHOR_ID
# WHERE B.CATEGORY = '경제'
# ORDER BY PUBLISHED_DATE